siemens_plc_interface:
  # Host of Siemens PLC server.
  plc_host: 192.168.58.20
  # Port of Siemens PLC server.
  plc_port: 502
  # Rate of Siemens PLC server.
  plc_rate: 20  # Hz
  # Whether reset the Siemens PLC client.
  reset_registers: True
  # Topic for subscribing msgs from Siemens PLC server.
  sub_topic: modbus_wrapper/output
  # Topic for publishing msgs to Siemens PLC server.
  pub_topic: modbus_wrapper/input
