siemens_plc_interface:
  # Host of Siemens PLC server.
  host: 192.168.0.1
  # Port of Siemens PLC server.
  port: 8080
  # Rate of Siemens PLC server.
  rate: 50
  # Whether reset the Siemens PLC client.
  reset_registers: True
  # Topic for subscriber of Siemens PLC server.
  sub_topic: modbus_wrapper/output
  # Topic for publisher of Siemens PLC server.
  pub_topic: modbus_wrapper/input
  
  # Name of laser switch topic from master hfd.
  laser_switch_topic: /hfd/master_hfd/laser_switch
